### ISSUE TITLE
Error in getting the fd of the listening socket

### ISSUE THREAD

**Issue by andyxning** [jeffallen/jra-go#2]
In `upgradable.go` we have a logic to get the `fd` of the listening socket. However, it is that we may be wrong in accessing the `fd`. 

As said in the [doc](https://golang.org/src/net/tcpsock_posix.go?s=9965:10017#L298), that the `fd` of the returned `File` is not the one as the requested. Then something is wrong.

> File returns a copy of the underlying os.File, set to blocking mode. It is the caller's responsibility to close f when finished. Closing l does not affect f, and closing f does not affect l.
> 
> The returned os.File's file descriptor is different from the connection's. Attempting to change properties of the original using this duplicate may or may not have the desired effect.

```
    tl := theStoppable.Listener.(*net.TCPListener)
    fl, err := tl.File()
    if err != nil {
        log.Fatal(err)
    }
    fd := fl.Fd()
```

**Comment by jeffallen** [comment]
This is an unsupported toy, I don't know if it even works these days.

If you have a fix, you may send it as a pull request.

**Comment by andyxning** [comment]
Ok, i will test it.
